#ifndef REGISTRY_H
#define REGISTRY_H

#define TASK_LOGGER 0
#define TASK_MONITOR 1
#define TASK_TCP 2

#define MSG_LOG 0
#define MSG_TIMEOUT_CONFIGURE 1
#define MSG_TIMEOUT_UPDATE 2
#define MSG_TIMEOUT_EXPIRED 3
#define MSG_SENSOR_DATA 4

#define SENSOR_TYPE_IMU1ACCEL 0
#define SENSOR_TYPE_IMU1GYRO 1
#define SENSOR_TYPE_TEMP1 2
#define SENSOR_TYPE_TEMP2 3
#define SENSOR_TYPE_PHOTO2 4
#define SENSOR_TYPE_HALL1 5
#define SENSOR_TYPE_PIEZO1 6

#endif